apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-models-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ngtukien/Documents/VDT_2026/15.Report
  claimRef:
    name: llama-models
    namespace: default